hooks:
  # hook scripts
  # - golangci-lint run
  pre-commit:
    # - golangci-lint run
    - husky lint-staged
    - make build
    # - go test -v ./...
  pre-push:
    - husky lint-staged
    - make build
  commit-msg:
    - husky lint-commit

# list staged files do some pre-process and git add
lint-staged:
  "*.go":
    - gofmt -l -w

# commit msg rule only support conventional commits
lint-commit:
  # could check if this exists
  email: "^(.+@theflurn.com)$"
  # optional custom types check regex
  types: "^(feat|fix|build|chore|ci|docs|perf|refactor|revert|style|test)$"
  # optional header check regex
  # header: "^(?P<type>\w+)(\((?P<scope>[\w/.-]+)\))?(?P<breaking>!)?:( +)?(?P<header>.+)"
